name: Update Prayer Times

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node update.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add prayer.json
          git commit -m "update prayer times" || exit 0
          git push
